#! /usr/bin/env bash
set -euo pipefail

# A command-line tool that computes the Dropbox-Content-Hash of the given file.

[ ! -e out ] || rm -r out
mkdir -p out
javac -d out src/*.java

exec java -cp out HashFile "$@"

